### ISSUE TITLE
请问对相机坐标系确定吗？

### ISSUE THREAD

**Issue by h-k8888** [skyrim835/LVI-SAM-modified#4]
您好，关于图
https://github.com/skyrim835/LVI-SAM-modified/blob/d035a501fb3bb04ff074a7e1f21a8bedf44cf3bf/images/LVI-SAM-original-coordinates.png
中的坐标系，我有个有疑问。
按照LVI-SAM的原版代码
https://github.com/TixiaoShan/LVI-SAM/blob/9b9ba85e300c382a272347b32af397ca3e8a78a5/src/visual_odometry/visual_feature/feature_tracker.h#L142
雷达系应该跟您的图一样，但是相机系应该是x向右，z向前，y向下吧。
请问您对图中相机的坐标系确定吗？

**Comment by skyrim835** [comment]
我也比较好奇这个问题，因为作者给出的imu_to_lidar可以通过逆时针旋转lidar的y轴180°得到，其结果与yaml文件中相同，cam_to_imu的值如果按照我给的示意图来可以线绕x轴逆时针旋转90°，再顺时针绕旋转后的z轴，再利用矩阵连续左乘可以得到和yaml文件中相同的值，但是如果按照x向右，z向前，y向下则无法通过上述规则得到。

**Comment by h-k8888** [comment]
方便加个私信吗？之后有问题可以一起交流？

**Comment by skyrim835** [comment]
没问题，那你发下你的微信号吧我这边加你。坐标的问题我跟小伙伴商量商量之后再传个新的

**Comment by h-k8888** [comment]
wxid_cezxmu0eom8y22

**Comment by skyrim835** [comment]
> wxid_cezxmu0eom8y22

emmm搜不着 你瞅下是不是通过微信号搜索没有开

**Comment by h-k8888** [comment]
emm...
更新了一下
Hk1911202
