### ISSUE TITLE
Question related to flashing in Rviz during LVI-SAM-modified

### ISSUE THREAD

**Issue by Taeyoung96** [skyrim835/LVI-SAM-modified#8]
@skyrim835   
Thanks for your great work!  
I have some questions about flashing in Rviz.  

When I run LVI-SAM modified with my custom dataset(Velodyne + realsense D435i), it blinks like the below.    
I mean the mapping is unstable.  

<p align="center"><img src="https://user-images.githubusercontent.com/41863759/181463428-0c709ebb-6266-4d56-9e7e-bb6f3f9b53e5.gif" width = "600" ></p>  

When I run [Faster-LIO](https://github.com/gaoxiang12/faster-lio), it works fine so I don't think this cause is a dataset problem.  

Did the same phenomenon occur when you run LVI-SAM-modified?  
If not, What part should I fix to solve the problem?  

I'd appreciate it if you could give me an answer.  

Thanks,

**Comment by skyrim835** [comment]
I didn't meat this problem,would you mind give me part of your datasets?

**Comment by skyrim835** [comment]
I didn't meet this problem,would you mind give me part of your datasets?

**Comment by Taeyoung96** [comment]
Thank you for your quick reply.  

The problem of blinking while modifying the rosbag file has been eliminated.  
Maybe it was a dataset record problem.  :sweat_smile:   
If I have any questions after turning it back to various rosbag file, I will leave an issue again.  

Thanks :smile:
